[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "20"

[build]
publish = ".vitepress/dist"
command = "pnpm run docs:build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
